import mongoose from "mongoose";
import "../config/env.js";
import connectDB from "../config/db.js";
import User from "../models/User.js";
import Category from "../models/Category.js";
import Food from "../models/Food.js";
import bcrypt from "bcryptjs";

connectDB();

const fallbackImage =
  "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1200&auto=format&fit=crop";

const categories = [
  { name: "Cơm healthy", slug: "com-healthy" },
  { name: "Salad", slug: "salad" },
  { name: "Món chay", slug: "mon-chay" },
  { name: "Món cho người tiểu đường", slug: "mon-cho-nguoi-tieu-duong" },
  { name: "Món giảm cân", slug: "mon-giam-can" },
  { name: "Món tăng cơ", slug: "mon-tang-co" },
  { name: "Món ít dầu mỡ", slug: "mon-it-dau-mo" },
  { name: "Món ăn gia đình", slug: "mon-an-gia-dinh" },
  { name: "Đồ uống lành mạnh", slug: "do-uong-lanh-manh" },
];

// Calo/100g theo bảng người dùng cung cấp từ Bộ Y tế/Viện Dinh dưỡng.
const caloriePer100g = {
  "Gạo nếp cái": 344,
  "Gạo tẻ giã": 344,
  "Gạo lứt": 345,
  "Bánh mì": 249,
  "Bánh phở": 143,
  Bún: 110,
  "Mì sợi": 349,
  "Miến dong": 332,
  "Khoai lang": 119,
  "Khoai tây": 93,
  "Thịt bò loại 1": 118,
  "Thịt gà ta": 199,
  "Thịt heo nạc": 139,
  "Chả lụa": 136,
  "Cá chép": 96,
  "Cá hồi": 136,
  "Cá ngừ": 87,
  "Cá thu": 166,
  "Mực tươi": 73,
  "Tôm biển": 82,
  "Trứng gà": 166,
  "Trứng vịt": 184,
  "Đậu cô ve": 73,
  "Đậu Hà Lan": 72,
  "Đậu phụ": 95,
  "Nấm hương khô": 274,
  "Nấm mèo": 304,
  "Bí xanh": 12,
  "Bí đỏ": 27,
  "Cà chua": 20,
  "Cà rốt": 39,
  "Cải bắp": 29,
  "Cải thìa": 17,
  "Cải xanh": 16,
  "Rau muống": 25,
  "Rau ngót": 35,
  "Củ cải trắng": 21,
  "Dưa chuột": 16,
  "Hạt sen tươi": 161,
  "Măng tây": 14,
  Mướp: 17,
  "Khổ qua": 16,
  "Súp lơ xanh": 26,
  Cam: 38,
  Chanh: 24,
  "Chuối tiêu": 97,
  "Dâu tây": 43,
  Dứa: 38,
  Lê: 45,
  Lựu: 70,
  Ổi: 38,
  "Nước cam tươi": 23,
  "Sữa bò tươi": 74,
  "Sữa chua": 61,
  "Nước dừa tươi": 19,
  "Pepsi không calo": 0,
};

const slugify = (value) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
    .replace(/đ/g, "d")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const kcal = (components) =>
  Math.round(
    components.reduce((total, item) => {
      const per100g = caloriePer100g[item.name];
      if (per100g === undefined) {
        throw new Error(`Missing calorie source for ingredient: ${item.name}`);
      }
      return total + (per100g * item.grams) / 100;
    }, 0),
  );

const ingredientCalories = (item) =>
  Math.round((caloriePer100g[item.name] * item.grams) / 100);

const ingredientText = (components) =>
  components.map(
    (item) => `${item.name} ${item.grams}g(${ingredientCalories(item)} calo)`,
  );

const estimateMacros = (calories, type) => {
  const ratios = {
    carb: [0.18, 0.58, 0.24],
    protein: [0.38, 0.38, 0.24],
    lowCarb: [0.42, 0.25, 0.33],
    drink: [0.08, 0.82, 0.1],
    balanced: [0.28, 0.48, 0.24],
  }[type || "balanced"];

  return {
    protein: Math.round((calories * ratios[0]) / 4),
    carbs: Math.round((calories * ratios[1]) / 4),
    fat: Math.round((calories * ratios[2]) / 9),
  };
};

const food = ({
  name,
  categorySlug,
  price,
  description,
  components,
  macroType = "balanced",
  sugar = 4,
  sodium = 320,
  fiber = 5,
  healthTags,
  suitableFor,
  warningFor = [],
  isVegetarian = false,
  image = fallbackImage,
}) => {
  const calories = kcal(components);
  const macros = estimateMacros(calories, macroType);

  return {
    name,
    slug: slugify(name),
    price,
    description,
    ingredients: ingredientText(components),
    nutrition: { calories, ...macros, sugar, sodium, fiber },
    healthTags,
    suitableFor,
    warningFor,
    images: [image],
    isVegetarian,
    isAvailable: true,
    stock: 100,
    categorySlug,
  };
};

const foods = [
  food({
    name: "Cơm gạo lứt ức gà rau củ",
    categorySlug: "com-healthy",
    price: 65000,
    description:
      "Khẩu phần cơm healthy dùng gạo lứt, thịt gà ta và rau củ trong bảng calo.",
    components: [
      { name: "Gạo lứt", grams: 100 },
      { name: "Thịt gà ta", grams: 80 },
      { name: "Súp lơ xanh", grams: 70 },
      { name: "Cà rốt", grams: 40 },
    ],
    image: "/foods/comgaoluc.jpg",
    macroType: "balanced",
    sugar: 4,
    sodium: 360,
    fiber: 7,
    healthTags: ["cơm healthy", "giàu đạm", "nhiều rau"],
    suitableFor: ["Người ăn healthy", "Người cần bữa trưa cân bằng"],
    image: "/foods/comgaoluc.jpg",
  }),
  food({
    name: "Cơm gạo lứt cá hồi măng tây",
    categorySlug: "com-healthy",
    price: 85000,
    description:
      "Cá hồi và măng tây kết hợp gạo lứt, calo tính theo gram từng nguyên liệu.",
    components: [
      { name: "Gạo lứt", grams: 100 },
      { name: "Cá hồi", grams: 100 },
      { name: "Măng tây", grams: 80 },
      { name: "Cà chua", grams: 50 },
    ],
    image: "/foods/cahoimangtay.jpg",
    macroType: "balanced",
    sugar: 3,
    sodium: 300,
    fiber: 6,
    healthTags: ["omega-3", "cơm healthy", "giàu đạm"],
    suitableFor: ["Người ăn healthy", "Người cần chất béo tốt"],
    warningFor: ["Dị ứng cá hồi hoặc hải sản"],
  }),
  food({
    name: "Cơm gạo tẻ bò súp lơ",
    categorySlug: "com-healthy",
    price: 76000,
    description: "Bữa cơm năng lượng vừa với gạo tẻ, bò nạc và súp lơ xanh.",
    components: [
      { name: "Gạo tẻ giã", grams: 95 },
      { name: "Thịt bò loại 1", grams: 100 },
      { name: "Súp lơ xanh", grams: 90 },
      { name: "Dưa chuột", grams: 50 },
    ],
    image: "/foods/boxaohanh.jpg",
    macroType: "balanced",
    sugar: 4,
    sodium: 390,
    fiber: 6,
    healthTags: ["giàu đạm", "nhiều rau", "cân bằng"],
    suitableFor: ["Người vận động", "Người cần bữa chính đủ chất"],
  }),
  food({
    name: "Cơm gạo lứt tôm đậu cô ve",
    categorySlug: "com-healthy",
    price: 69000,
    description: "Tôm biển ít calo, ăn cùng gạo lứt và đậu cô ve.",
    components: [
      { name: "Gạo lứt", grams: 100 },
      { name: "Tôm biển", grams: 100 },
      { name: "Đậu cô ve", grams: 70 },
      { name: "Cà rốt", grams: 40 },
    ],
    image: "/foods/tomdau.jpg",
    macroType: "balanced",
    sugar: 5,
    sodium: 430,
    fiber: 7,
    healthTags: ["ít béo", "giàu đạm", "cơm healthy"],
    suitableFor: ["Người ăn healthy", "Người muốn bữa nhẹ"],
    warningFor: ["Dị ứng tôm hoặc hải sản"],
  }),
  food({
    name: "Cơm gạo lứt đậu phụ cải thìa",
    categorySlug: "com-healthy",
    price: 56000,
    description: "Bữa healthy chay với gạo lứt, đậu phụ và cải thìa.",
    components: [
      { name: "Gạo lứt", grams: 100 },
      { name: "Đậu phụ", grams: 120 },
      { name: "Cải thìa", grams: 90 },
      { name: "Cà chua", grams: 50 },
    ],
    image: "/foods/dauphu.jpg",
    macroType: "carb",
    sugar: 4,
    sodium: 300,
    fiber: 8,
    healthTags: ["món chay", "đạm thực vật", "cơm healthy"],
    suitableFor: ["Người ăn chay", "Người ăn healthy"],
    isVegetarian: true,
  }),
  food({
    name: "Cơm khoai lang gà cải xanh",
    categorySlug: "com-healthy",
    price: 62000,
    description:
      "Khoai lang và thịt gà ta tạo khẩu phần no lâu, dùng cùng cải xanh.",
    components: [
      { name: "Khoai lang", grams: 150 },
      { name: "Thịt gà ta", grams: 90 },
      { name: "Cải xanh", grams: 90 },
      { name: "Dưa chuột", grams: 50 },
    ],
    image: "/foods/khoailang.jpg",
    macroType: "balanced",
    sugar: 8,
    sodium: 330,
    fiber: 8,
    healthTags: ["no lâu", "giàu đạm", "nhiều rau"],
    suitableFor: ["Người ăn healthy", "Người cần kiểm soát năng lượng"],
  }),

  food({
    name: "Salad gà cải bắp dưa chuột",
    categorySlug: "salad",
    price: 52000,
    description: "Salad ít tinh bột với thịt gà ta, cải bắp và dưa chuột.",
    components: [
      { name: "Thịt gà ta", grams: 90 },
      { name: "Cải bắp", grams: 100 },
      { name: "Dưa chuột", grams: 80 },
      { name: "Cà chua", grams: 60 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 280,
    fiber: 6,
    healthTags: ["salad", "ít tinh bột", "giàu đạm"],
    suitableFor: ["Người giảm cân", "Người ăn tối nhẹ"],
  }),
  food({
    name: "Salad cá ngừ trứng gà",
    categorySlug: "salad",
    price: 62000,
    description: "Cá ngừ và trứng gà cung cấp đạm, rau củ giúp tăng chất xơ.",
    components: [
      { name: "Cá ngừ", grams: 100 },
      { name: "Trứng gà", grams: 50 },
      { name: "Cải bắp", grams: 80 },
      { name: "Dưa chuột", grams: 70 },
    ],
    macroType: "lowCarb",
    sugar: 4,
    sodium: 420,
    fiber: 5,
    healthTags: ["salad", "giàu đạm", "ít tinh bột"],
    suitableFor: ["Người tập luyện", "Người kiểm soát cân nặng"],
    warningFor: ["Dị ứng cá hoặc trứng"],
  }),
  food({
    name: "Salad đậu phụ cà chua",
    categorySlug: "salad",
    price: 48000,
    description: "Salad chay từ đậu phụ, cà chua, dưa chuột và cải xanh.",
    components: [
      { name: "Đậu phụ", grams: 120 },
      { name: "Cà chua", grams: 100 },
      { name: "Dưa chuột", grams: 80 },
      { name: "Cải xanh", grams: 60 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 240,
    fiber: 5,
    healthTags: ["salad", "món chay", "đạm thực vật"],
    suitableFor: ["Người ăn chay", "Người ăn nhẹ"],
    isVegetarian: true,
  }),
  food({
    name: "Salad bò măng tây",
    categorySlug: "salad",
    price: 72000,
    description: "Bò nạc và măng tây trong khẩu phần salad giàu đạm.",
    components: [
      { name: "Thịt bò loại 1", grams: 100 },
      { name: "Măng tây", grams: 100 },
      { name: "Cà chua", grams: 70 },
      { name: "Cải bắp", grams: 70 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 330,
    fiber: 6,
    healthTags: ["salad", "giàu đạm", "giàu sắt"],
    suitableFor: ["Người vận động", "Người cần bổ sung đạm"],
  }),
  food({
    name: "Salad tôm súp lơ xanh",
    categorySlug: "salad",
    price: 68000,
    description: "Tôm biển, súp lơ xanh và dưa chuột tạo món salad ít calo.",
    components: [
      { name: "Tôm biển", grams: 110 },
      { name: "Súp lơ xanh", grams: 100 },
      { name: "Dưa chuột", grams: 80 },
      { name: "Cà rốt", grams: 50 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 380,
    fiber: 6,
    healthTags: ["salad", "ít calo", "giàu đạm"],
    suitableFor: ["Người giảm cân", "Người ăn nhẹ"],
    warningFor: ["Dị ứng tôm hoặc hải sản"],
  }),
  food({
    name: "Salad trái cây sữa chua",
    categorySlug: "salad",
    price: 49000,
    description:
      "Salad trái cây dùng cam, dâu tây, lê và sữa chua trong bảng calo.",
    components: [
      { name: "Cam", grams: 80 },
      { name: "Dâu tây", grams: 80 },
      { name: "Lê", grams: 80 },
      { name: "Sữa chua", grams: 100 },
    ],
    macroType: "drink",
    sugar: 28,
    sodium: 90,
    fiber: 5,
    healthTags: ["salad", "trái cây", "bữa phụ"],
    suitableFor: ["Người cần bữa phụ", "Người thích món mát"],
    warningFor: ["Người cần hạn chế đường trái cây"],
    isVegetarian: true,
  }),

  food({
    name: "Đậu phụ sốt cà chua",
    categorySlug: "mon-chay",
    price: 45000,
    description:
      "Món chay đơn giản từ đậu phụ và cà chua, calo tính theo khẩu phần.",
    components: [
      { name: "Đậu phụ", grams: 180 },
      { name: "Cà chua", grams: 120 },
      { name: "Cải thìa", grams: 80 },
    ],
    macroType: "lowCarb",
    sugar: 7,
    sodium: 300,
    fiber: 5,
    healthTags: ["món chay", "đạm thực vật", "ít calo"],
    suitableFor: ["Người ăn chay", "Người ăn nhẹ"],
    isVegetarian: true,
  }),
  food({
    name: "Cơm gạo lứt đậu phụ",
    categorySlug: "mon-chay",
    price: 54000,
    description: "Cơm chay no lâu với gạo lứt, đậu phụ và rau củ.",
    components: [
      { name: "Gạo lứt", grams: 90 },
      { name: "Đậu phụ", grams: 120 },
      { name: "Đậu cô ve", grams: 60 },
      { name: "Cà rốt", grams: 50 },
    ],
    macroType: "carb",
    sugar: 5,
    sodium: 310,
    fiber: 8,
    healthTags: ["món chay", "no lâu", "giàu chất xơ"],
    suitableFor: ["Người ăn chay", "Người cần bữa chính"],
    isVegetarian: true,
  }),
  food({
    name: "Miến dong rau củ chay",
    categorySlug: "mon-chay",
    price: 52000,
    description: "Miến dong kết hợp rau củ và đậu phụ, phù hợp bữa chay nhẹ.",
    components: [
      { name: "Miến dong", grams: 55 },
      { name: "Đậu phụ", grams: 90 },
      { name: "Cải thìa", grams: 80 },
      { name: "Cà rốt", grams: 40 },
    ],
    macroType: "carb",
    sugar: 4,
    sodium: 360,
    fiber: 5,
    healthTags: ["món chay", "bữa nhẹ", "rau củ"],
    suitableFor: ["Người ăn chay", "Người thích món nước"],
    isVegetarian: true,
  }),
  food({
    name: "Canh bí xanh đậu phụ",
    categorySlug: "mon-chay",
    price: 39000,
    description: "Canh thanh nhẹ với bí xanh và đậu phụ, calo thấp.",
    components: [
      { name: "Bí xanh", grams: 220 },
      { name: "Đậu phụ", grams: 120 },
      { name: "Cà rốt", grams: 40 },
    ],
    macroType: "lowCarb",
    sugar: 4,
    sodium: 220,
    fiber: 4,
    healthTags: ["món chay", "ít calo", "thanh nhẹ"],
    suitableFor: ["Người ăn chay", "Người giảm cân"],
    isVegetarian: true,
  }),
  food({
    name: "Khổ qua nhồi đậu phụ nấm mèo",
    categorySlug: "mon-chay",
    price: 50000,
    description: "Khổ qua nhồi đậu phụ và nấm mèo, món chay nhiều chất xơ.",
    components: [
      { name: "Khổ qua", grams: 180 },
      { name: "Đậu phụ", grams: 120 },
      { name: "Nấm mèo", grams: 10 },
      { name: "Cà rốt", grams: 30 },
    ],
    macroType: "lowCarb",
    sugar: 4,
    sodium: 260,
    fiber: 7,
    healthTags: ["món chay", "giàu chất xơ", "ít calo"],
    suitableFor: ["Người ăn chay", "Người cần món thanh"],
    isVegetarian: true,
  }),
  food({
    name: "Bí đỏ hấp hạt sen",
    categorySlug: "mon-chay",
    price: 47000,
    description: "Bí đỏ và hạt sen tạo món chay mềm, dễ ăn.",
    components: [
      { name: "Bí đỏ", grams: 180 },
      { name: "Hạt sen tươi", grams: 80 },
      { name: "Cà rốt", grams: 40 },
    ],
    macroType: "carb",
    sugar: 8,
    sodium: 120,
    fiber: 7,
    healthTags: ["món chay", "mềm dễ ăn", "bữa nhẹ"],
    suitableFor: ["Người ăn chay", "Người lớn tuổi"],
    isVegetarian: true,
  }),

  food({
    name: "Gà ta cải xanh ít tinh bột",
    categorySlug: "mon-cho-nguoi-tieu-duong",
    price: 62000,
    description: "Khẩu phần ít tinh bột với thịt gà ta, cải xanh và dưa chuột.",
    components: [
      { name: "Thịt gà ta", grams: 100 },
      { name: "Cải xanh", grams: 100 },
      { name: "Dưa chuột", grams: 80 },
      { name: "Cà chua", grams: 60 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 300,
    fiber: 5,
    healthTags: ["ít tinh bột", "ít đường", "giàu đạm"],
    suitableFor: ["Người cần kiểm soát đường huyết", "Người ăn tối nhẹ"],
  }),
  food({
    name: "Cá hồi măng tây",
    categorySlug: "mon-cho-nguoi-tieu-duong",
    price: 85000,
    description: "Cá hồi và măng tây, không dùng tinh bột chính.",
    components: [
      { name: "Cá hồi", grams: 120 },
      { name: "Măng tây", grams: 120 },
      { name: "Cà chua", grams: 60 },
      { name: "Dưa chuột", grams: 60 },
    ],
    macroType: "lowCarb",
    sugar: 4,
    sodium: 280,
    fiber: 4,
    healthTags: ["ít tinh bột", "omega-3", "ít đường"],
    suitableFor: ["Người cần kiểm soát đường huyết", "Người ăn low-carb"],
    warningFor: ["Dị ứng cá hồi hoặc hải sản"],
  }),
  food({
    name: "Đậu phụ cải thìa cà chua",
    categorySlug: "mon-cho-nguoi-tieu-duong",
    price: 48000,
    description:
      "Đạm thực vật, rau xanh và cà chua, không thêm nguồn đường ngoài bảng.",
    components: [
      { name: "Đậu phụ", grams: 150 },
      { name: "Cải thìa", grams: 120 },
      { name: "Cà chua", grams: 80 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 260,
    fiber: 5,
    healthTags: ["ít đường", "đạm thực vật", "món chay"],
    suitableFor: ["Người cần kiểm soát đường huyết", "Người ăn chay"],
    isVegetarian: true,
  }),
  food({
    name: "Canh khổ qua thịt nạc",
    categorySlug: "mon-cho-nguoi-tieu-duong",
    price: 56000,
    description: "Khổ qua và thịt heo nạc, ít calo và ít tinh bột.",
    components: [
      { name: "Khổ qua", grams: 180 },
      { name: "Thịt heo nạc", grams: 80 },
      { name: "Nấm mèo", grams: 8 },
      { name: "Cà rốt", grams: 30 },
    ],
    macroType: "lowCarb",
    sugar: 4,
    sodium: 360,
    fiber: 6,
    healthTags: ["ít tinh bột", "ít đường", "món canh"],
    suitableFor: ["Người cần kiểm soát đường huyết", "Người thích món canh"],
  }),
  food({
    name: "Trứng gà súp lơ xanh",
    categorySlug: "mon-cho-nguoi-tieu-duong",
    price: 45000,
    description: "Trứng gà và súp lơ xanh cho bữa sáng ít tinh bột.",
    components: [
      { name: "Trứng gà", grams: 100 },
      { name: "Súp lơ xanh", grams: 120 },
      { name: "Cà chua", grams: 60 },
    ],
    macroType: "lowCarb",
    sugar: 4,
    sodium: 280,
    fiber: 5,
    healthTags: ["ít tinh bột", "giàu đạm", "bữa sáng"],
    suitableFor: ["Người cần kiểm soát đường huyết", "Người ăn sáng nhẹ"],
    warningFor: ["Dị ứng trứng"],
  }),
  food({
    name: "Tôm biển bí xanh",
    categorySlug: "mon-cho-nguoi-tieu-duong",
    price: 65000,
    description: "Tôm biển và bí xanh, khẩu phần ít năng lượng và ít đường.",
    components: [
      { name: "Tôm biển", grams: 120 },
      { name: "Bí xanh", grams: 180 },
      { name: "Cải thìa", grams: 80 },
    ],
    macroType: "lowCarb",
    sugar: 3,
    sodium: 390,
    fiber: 4,
    healthTags: ["ít đường", "ít calo", "giàu đạm"],
    suitableFor: ["Người cần kiểm soát đường huyết", "Người giảm cân"],
    warningFor: ["Dị ứng tôm hoặc hải sản"],
  }),

  food({
    name: "Gà ta khoai lang cải xanh",
    categorySlug: "mon-giam-can",
    price: 60000,
    description:
      "Khoai lang lượng vừa, gà ta và cải xanh giúp no lâu khi giảm cân.",
    components: [
      { name: "Thịt gà ta", grams: 90 },
      { name: "Khoai lang", grams: 120 },
      { name: "Cải xanh", grams: 100 },
      { name: "Dưa chuột", grams: 60 },
    ],
    macroType: "balanced",
    sugar: 8,
    sodium: 300,
    fiber: 8,
    healthTags: ["giảm cân", "no lâu", "giàu đạm"],
    suitableFor: ["Người giảm cân", "Người cần bữa đủ chất"],
  }),
  food({
    name: "Cá ngừ dưa chuột cà chua",
    categorySlug: "mon-giam-can",
    price: 62000,
    description: "Cá ngừ ít calo ăn cùng rau củ tươi.",
    components: [
      { name: "Cá ngừ", grams: 120 },
      { name: "Dưa chuột", grams: 100 },
      { name: "Cà chua", grams: 80 },
      { name: "Cải bắp", grams: 80 },
    ],
    macroType: "lowCarb",
    sugar: 6,
    sodium: 320,
    fiber: 5,
    healthTags: ["giảm cân", "ít calo", "giàu đạm"],
    suitableFor: ["Người giảm cân", "Người ăn tối nhẹ"],
    warningFor: ["Dị ứng cá"],
  }),
  food({
    name: "Cá chép hấp bí xanh",
    categorySlug: "mon-giam-can",
    price: 64000,
    description: "Cá chép và bí xanh, món hấp nhẹ cho người giảm cân.",
    components: [
      { name: "Cá chép", grams: 130 },
      { name: "Bí xanh", grams: 180 },
      { name: "Cải thìa", grams: 80 },
    ],
    macroType: "lowCarb",
    sugar: 3,
    sodium: 300,
    fiber: 4,
    healthTags: ["giảm cân", "ít calo", "món hấp"],
    suitableFor: ["Người giảm cân", "Người thích món cá"],
    warningFor: ["Dị ứng cá"],
  }),
  food({
    name: "Bún gà cải bắp",
    categorySlug: "mon-giam-can",
    price: 55000,
    description: "Bún lượng vừa với gà ta và cải bắp, phù hợp bữa trưa nhẹ.",
    components: [
      { name: "Bún", grams: 100 },
      { name: "Thịt gà ta", grams: 80 },
      { name: "Cải bắp", grams: 100 },
      { name: "Dưa chuột", grams: 60 },
    ],
    macroType: "balanced",
    sugar: 5,
    sodium: 360,
    fiber: 5,
    healthTags: ["giảm cân", "bữa nhẹ", "giàu đạm"],
    suitableFor: ["Người giảm cân", "Người thích món bún"],
  }),
  food({
    name: "Súp bí đỏ gà ta",
    categorySlug: "mon-giam-can",
    price: 50000,
    description: "Súp mềm từ bí đỏ và thịt gà ta, dễ ăn và năng lượng vừa.",
    components: [
      { name: "Bí đỏ", grams: 200 },
      { name: "Thịt gà ta", grams: 70 },
      { name: "Cà rốt", grams: 40 },
    ],
    macroType: "balanced",
    sugar: 9,
    sodium: 260,
    fiber: 5,
    healthTags: ["giảm cân", "món mềm", "bữa tối nhẹ"],
    suitableFor: ["Người giảm cân", "Người cần món dễ tiêu"],
  }),
  food({
    name: "Trứng gà rau củ hấp",
    categorySlug: "mon-giam-can",
    price: 46000,
    description: "Trứng gà hấp với súp lơ, cà rốt và cải thìa.",
    components: [
      { name: "Trứng gà", grams: 80 },
      { name: "Súp lơ xanh", grams: 100 },
      { name: "Cải thìa", grams: 80 },
      { name: "Cà rốt", grams: 40 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 240,
    fiber: 6,
    healthTags: ["giảm cân", "ít tinh bột", "nhiều rau"],
    suitableFor: ["Người giảm cân", "Người ăn nhẹ"],
    warningFor: ["Dị ứng trứng"],
  }),

  food({
    name: "Gà ta gạo lứt khoai lang",
    categorySlug: "mon-tang-co",
    price: 72000,
    description:
      "Bữa tăng cơ nhiều năng lượng từ gà ta, gạo lứt và khoai lang.",
    components: [
      { name: "Thịt gà ta", grams: 140 },
      { name: "Gạo lứt", grams: 110 },
      { name: "Khoai lang", grams: 100 },
      { name: "Súp lơ xanh", grams: 80 },
    ],
    macroType: "protein",
    sugar: 8,
    sodium: 420,
    fiber: 9,
    healthTags: ["tăng cơ", "giàu đạm", "nhiều năng lượng"],
    suitableFor: ["Người tập gym", "Người cần tăng cơ"],
  }),
  food({
    name: "Bò gạo tẻ khoai tây",
    categorySlug: "mon-tang-co",
    price: 82000,
    description: "Bò nạc, gạo tẻ và khoai tây cho ngày vận động nhiều.",
    components: [
      { name: "Thịt bò loại 1", grams: 140 },
      { name: "Gạo tẻ giã", grams: 110 },
      { name: "Khoai tây", grams: 120 },
      { name: "Măng tây", grams: 80 },
    ],
    macroType: "protein",
    sugar: 5,
    sodium: 460,
    fiber: 7,
    healthTags: ["tăng cơ", "giàu đạm", "giàu năng lượng"],
    suitableFor: ["Người tập gym", "Người vận động mạnh"],
  }),
  food({
    name: "Cá ngừ gạo lứt đậu Hà Lan",
    categorySlug: "mon-tang-co",
    price: 78000,
    description: "Cá ngừ giàu đạm kết hợp gạo lứt và đậu Hà Lan.",
    components: [
      { name: "Cá ngừ", grams: 150 },
      { name: "Gạo lứt", grams: 110 },
      { name: "Đậu Hà Lan", grams: 80 },
      { name: "Cà rốt", grams: 50 },
    ],
    macroType: "protein",
    sugar: 6,
    sodium: 420,
    fiber: 9,
    healthTags: ["tăng cơ", "giàu đạm", "giàu chất xơ"],
    suitableFor: ["Người tập gym", "Người cần tăng cơ nạc"],
    warningFor: ["Dị ứng cá"],
  }),
  food({
    name: "Tôm biển trứng gạo lứt",
    categorySlug: "mon-tang-co",
    price: 78000,
    description: "Tôm biển và trứng gà cùng gạo lứt tạo bữa giàu đạm.",
    components: [
      { name: "Tôm biển", grams: 130 },
      { name: "Trứng gà", grams: 60 },
      { name: "Gạo lứt", grams: 110 },
      { name: "Đậu cô ve", grams: 70 },
    ],
    macroType: "protein",
    sugar: 5,
    sodium: 520,
    fiber: 8,
    healthTags: ["tăng cơ", "giàu đạm", "cân bằng"],
    suitableFor: ["Người tập gym", "Người cần phục hồi sau tập"],
    warningFor: ["Dị ứng tôm hoặc trứng"],
  }),
  food({
    name: "Mì sợi bò cải xanh",
    categorySlug: "mon-tang-co",
    price: 76000,
    description: "Mì sợi và bò nạc cho khẩu phần nhiều năng lượng.",
    components: [
      { name: "Mì sợi", grams: 80 },
      { name: "Thịt bò loại 1", grams: 120 },
      { name: "Cải xanh", grams: 100 },
      { name: "Cà chua", grams: 70 },
    ],
    macroType: "protein",
    sugar: 5,
    sodium: 540,
    fiber: 6,
    healthTags: ["tăng cơ", "giàu năng lượng", "giàu đạm"],
    suitableFor: ["Người tập gym", "Người vận động nhiều"],
  }),
  food({
    name: "Cơm trứng gà thịt nạc",
    categorySlug: "mon-tang-co",
    price: 68000,
    description:
      "Cơm gạo tẻ, trứng gà và thịt heo nạc cho bữa chính giàu năng lượng.",
    components: [
      { name: "Gạo tẻ giã", grams: 110 },
      { name: "Trứng gà", grams: 80 },
      { name: "Thịt heo nạc", grams: 90 },
      { name: "Cải thìa", grams: 80 },
    ],
    macroType: "protein",
    sugar: 4,
    sodium: 500,
    fiber: 5,
    healthTags: ["tăng cơ", "giàu đạm", "bữa chính"],
    suitableFor: ["Người tập gym", "Người cần bữa no lâu"],
    warningFor: ["Dị ứng trứng"],
  }),

  food({
    name: "Cá chép hấp cải thìa",
    categorySlug: "mon-it-dau-mo",
    price: 69000,
    description: "Cá chép hấp cùng cải thìa, không dùng nguyên liệu chiên xào.",
    components: [
      { name: "Cá chép", grams: 140 },
      { name: "Cải thìa", grams: 120 },
      { name: "Cà rốt", grams: 50 },
    ],
    macroType: "lowCarb",
    sugar: 4,
    sodium: 300,
    fiber: 5,
    healthTags: ["ít dầu mỡ", "món hấp", "giàu đạm"],
    suitableFor: ["Người ăn ít dầu", "Người lớn tuổi"],
    warningFor: ["Dị ứng cá"],
  }),
  food({
    name: "Gà ta hấp bí xanh",
    categorySlug: "mon-it-dau-mo",
    price: 65000,
    description: "Thịt gà ta và bí xanh, khẩu phần ít dầu mỡ.",
    components: [
      { name: "Thịt gà ta", grams: 110 },
      { name: "Bí xanh", grams: 180 },
      { name: "Dưa chuột", grams: 70 },
    ],
    macroType: "lowCarb",
    sugar: 3,
    sodium: 280,
    fiber: 4,
    healthTags: ["ít dầu mỡ", "giàu đạm", "ít tinh bột"],
    suitableFor: ["Người giảm cân", "Người ăn ít dầu"],
  }),
  food({
    name: "Tôm biển hấp súp lơ xanh",
    categorySlug: "mon-it-dau-mo",
    price: 70000,
    description: "Tôm biển hấp và súp lơ xanh, calo thấp.",
    components: [
      { name: "Tôm biển", grams: 130 },
      { name: "Súp lơ xanh", grams: 120 },
      { name: "Cà rốt", grams: 50 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 360,
    fiber: 6,
    healthTags: ["ít dầu mỡ", "ít calo", "giàu đạm"],
    suitableFor: ["Người ăn ít dầu", "Người giảm cân"],
    warningFor: ["Dị ứng tôm hoặc hải sản"],
  }),
  food({
    name: "Đậu phụ hấp nấm hương",
    categorySlug: "mon-it-dau-mo",
    price: 48000,
    description: "Đậu phụ và nấm hương hấp, món chay ít dầu.",
    components: [
      { name: "Đậu phụ", grams: 160 },
      { name: "Nấm hương khô", grams: 12 },
      { name: "Cải thìa", grams: 100 },
    ],
    macroType: "lowCarb",
    sugar: 3,
    sodium: 260,
    fiber: 5,
    healthTags: ["ít dầu mỡ", "món chay", "đạm thực vật"],
    suitableFor: ["Người ăn chay", "Người cần món nhẹ"],
    isVegetarian: true,
  }),
  food({
    name: "Canh bí xanh thịt nạc",
    categorySlug: "mon-it-dau-mo",
    price: 50000,
    description: "Canh bí xanh với thịt heo nạc, thanh nhẹ và ít calo.",
    components: [
      { name: "Bí xanh", grams: 220 },
      { name: "Thịt heo nạc", grams: 80 },
      { name: "Cà rốt", grams: 40 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 320,
    fiber: 5,
    healthTags: ["ít dầu mỡ", "món canh", "thanh nhẹ"],
    suitableFor: ["Gia đình", "Người ăn ít dầu"],
  }),
  food({
    name: "Mực tươi hấp dưa chuột",
    categorySlug: "mon-it-dau-mo",
    price: 74000,
    description: "Mực tươi hấp ăn cùng dưa chuột và cà chua.",
    components: [
      { name: "Mực tươi", grams: 150 },
      { name: "Dưa chuột", grams: 100 },
      { name: "Cà chua", grams: 80 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 380,
    fiber: 4,
    healthTags: ["ít dầu mỡ", "giàu đạm", "hải sản"],
    suitableFor: ["Người ăn ít dầu", "Người thích hải sản"],
    warningFor: ["Dị ứng mực hoặc hải sản"],
  }),

  food({
    name: "Cá thu cà chua",
    categorySlug: "mon-an-gia-dinh",
    price: 70000,
    description: "Món gia đình từ cá thu và cà chua, calo tính theo bảng.",
    components: [
      { name: "Cá thu", grams: 120 },
      { name: "Cà chua", grams: 140 },
      { name: "Cải thìa", grams: 80 },
    ],
    macroType: "balanced",
    sugar: 8,
    sodium: 520,
    fiber: 4,
    healthTags: ["món gia đình", "giàu đạm", "món cá"],
    suitableFor: ["Gia đình", "Người cần bữa cơm đủ chất"],
    warningFor: ["Dị ứng cá"],
  }),
  food({
    name: "Thịt heo nạc trứng vịt",
    categorySlug: "mon-an-gia-dinh",
    price: 68000,
    description: "Khẩu phần gia đình với thịt heo nạc và trứng vịt lượng vừa.",
    components: [
      { name: "Thịt heo nạc", grams: 90 },
      { name: "Trứng vịt", grams: 70 },
      { name: "Dưa chuột", grams: 80 },
      { name: "Cà chua", grams: 60 },
    ],
    macroType: "balanced",
    sugar: 5,
    sodium: 620,
    fiber: 3,
    healthTags: ["món gia đình", "giàu đạm", "đậm vị"],
    suitableFor: ["Gia đình", "Người cần bữa chính"],
    warningFor: ["Dị ứng trứng", "Người cần hạn chế cholesterol"],
  }),
  food({
    name: "Canh cá chép bí xanh",
    categorySlug: "mon-an-gia-dinh",
    price: 62000,
    description: "Canh cá chép với bí xanh và cà chua, nhẹ bụng cho bữa cơm.",
    components: [
      { name: "Cá chép", grams: 120 },
      { name: "Bí xanh", grams: 180 },
      { name: "Cà chua", grams: 80 },
    ],
    macroType: "lowCarb",
    sugar: 5,
    sodium: 420,
    fiber: 4,
    healthTags: ["món gia đình", "món canh", "dễ ăn"],
    suitableFor: ["Gia đình", "Người thích món canh"],
    warningFor: ["Dị ứng cá"],
  }),
  food({
    name: "Bò xào súp lơ xanh",
    categorySlug: "mon-an-gia-dinh",
    price: 72000,
    description: "Bò nạc và súp lơ xanh, món gia đình giàu đạm.",
    components: [
      { name: "Thịt bò loại 1", grams: 120 },
      { name: "Súp lơ xanh", grams: 120 },
      { name: "Cà rốt", grams: 50 },
    ],
    macroType: "balanced",
    sugar: 5,
    sodium: 500,
    fiber: 6,
    healthTags: ["món gia đình", "giàu đạm", "nhiều rau"],
    suitableFor: ["Gia đình", "Người vận động"],
  }),
  food({
    name: "Gà ta rau ngót",
    categorySlug: "mon-an-gia-dinh",
    price: 59000,
    description: "Gà ta nấu rau ngót, món canh quen thuộc cho gia đình.",
    components: [
      { name: "Thịt gà ta", grams: 100 },
      { name: "Rau ngót", grams: 120 },
      { name: "Cà rốt", grams: 40 },
    ],
    macroType: "lowCarb",
    sugar: 4,
    sodium: 360,
    fiber: 5,
    healthTags: ["món gia đình", "món canh", "giàu đạm"],
    suitableFor: ["Gia đình", "Người cần món dễ ăn"],
  }),
  food({
    name: "Trứng gà thịt nạc hấp",
    categorySlug: "mon-an-gia-dinh",
    price: 52000,
    description: "Trứng gà hấp thịt heo nạc, mềm và dễ ăn.",
    components: [
      { name: "Trứng gà", grams: 100 },
      { name: "Thịt heo nạc", grams: 70 },
      { name: "Nấm mèo", grams: 8 },
      { name: "Cà rốt", grams: 30 },
    ],
    macroType: "balanced",
    sugar: 3,
    sodium: 420,
    fiber: 3,
    healthTags: ["món gia đình", "mềm dễ ăn", "giàu đạm"],
    suitableFor: ["Gia đình", "Trẻ em", "Người cần món mềm"],
    warningFor: ["Dị ứng trứng"],
  }),

  food({
    name: "Nước cam tươi",
    categorySlug: "do-uong-lanh-manh",
    price: 35000,
    description:
      "Đồ uống dùng nước cam tươi trong bảng calo, không thêm nguyên liệu ngoài bảng.",
    components: [{ name: "Nước cam tươi", grams: 250 }],
    macroType: "drink",
    sugar: 21,
    sodium: 5,
    fiber: 0,
    healthTags: ["đồ uống", "vitamin C", "ít béo"],
    suitableFor: ["Người cần giải khát", "Người thích vị cam"],
    warningFor: ["Người cần hạn chế đường trái cây"],
    isVegetarian: true,
    image: "/foods/nuoccam.jpg",
  }),
  food({
    name: "Sữa chua dâu tây",
    categorySlug: "do-uong-lanh-manh",
    price: 42000,
    description: "Sữa chua và dâu tây, khẩu phần bữa phụ mát nhẹ.",
    components: [
      { name: "Sữa chua", grams: 150 },
      { name: "Dâu tây", grams: 100 },
    ],
    macroType: "drink",
    sugar: 18,
    sodium: 80,
    fiber: 3,
    healthTags: ["bữa phụ", "trái cây", "sữa chua"],
    suitableFor: ["Người cần bữa phụ", "Người thích món mát"],
    warningFor: ["Không phù hợp người dị ứng sữa"],
    isVegetarian: true,
    image: "/foods/dautay.jpg",
  }),
  food({
    name: "Sữa bò tươi chuối",
    categorySlug: "do-uong-lanh-manh",
    price: 43000,
    description: "Sữa bò tươi và chuối tiêu, giàu năng lượng tự nhiên.",
    components: [
      { name: "Sữa bò tươi", grams: 180 },
      { name: "Chuối tiêu", grams: 90 },
    ],
    macroType: "drink",
    sugar: 24,
    sodium: 90,
    fiber: 2,
    healthTags: ["bữa phụ", "năng lượng vừa", "sữa tươi"],
    suitableFor: ["Người cần bữa phụ", "Người vận động"],
    warningFor: ["Không phù hợp người dị ứng sữa"],
    isVegetarian: true,
    image: "/foods/suachuoi.jpg",
  }),
  food({
    name: "Sinh tố cam dâu sữa chua",
    categorySlug: "do-uong-lanh-manh",
    price: 45000,
    description:
      "Cam, dâu tây và sữa chua, calo tính theo gram từng thành phần.",
    components: [
      { name: "Cam", grams: 120 },
      { name: "Dâu tây", grams: 80 },
      { name: "Sữa chua", grams: 120 },
    ],
    macroType: "drink",
    sugar: 24,
    sodium: 70,
    fiber: 4,
    healthTags: ["sinh tố", "vitamin", "bữa phụ"],
    suitableFor: ["Người thích sinh tố", "Người cần bổ sung trái cây"],
    warningFor: ["Không phù hợp người dị ứng sữa"],
    isVegetarian: true,
    image: "/foods/camdau.jpg",
  }),
  food({
    name: "Ổi lê ép lạnh",
    categorySlug: "do-uong-lanh-manh",
    price: 38000,
    description: "Đồ uống trái cây từ ổi và lê, không thêm đường.",
    components: [
      { name: "Ổi", grams: 150 },
      { name: "Lê", grams: 100 },
      { name: "Chanh", grams: 10 },
    ],
    image: "/foods/oile.jpg",
    macroType: "drink",
    sugar: 22,
    sodium: 5,
    fiber: 7,
    healthTags: ["đồ uống", "trái cây", "không thêm đường"],
    suitableFor: ["Người cần giải khát", "Người thích vị thanh"],
    warningFor: ["Người cần hạn chế đường trái cây"],
    isVegetarian: true,
  }),
  food({
    name: "Sữa hạt sen tươi",
    categorySlug: "do-uong-lanh-manh",
    price: 44000,
    description: "Sữa hạt sen dùng hạt sen tươi và sữa bò tươi theo bảng calo.",
    components: [
      { name: "Hạt sen tươi", grams: 80 },
      { name: "Sữa bò tươi", grams: 150 },
    ],
    image: "/foods/suahatsen.jpg",
    macroType: "drink",
    sugar: 12,
    sodium: 85,
    fiber: 4,
    healthTags: ["đồ uống", "hạt sen", "bữa phụ"],
    suitableFor: ["Người cần bữa phụ", "Người thích sữa hạt"],
    warningFor: ["Không phù hợp người dị ứng sữa"],
    isVegetarian: true,
  }),
  food({
    name: "Nước dừa tươi",
    categorySlug: "do-uong-lanh-manh",
    price: 35000,
    description:
      "Nước dừa tươi nguyên chất, không thêm đường; calo tính theo 19 kcal/100g.",
    components: [{ name: "Nước dừa tươi", grams: 300 }],
    macroType: "drink",
    sugar: 14,
    sodium: 75,
    fiber: 0,
    healthTags: ["đồ uống", "giải khát", "không thêm đường"],
    suitableFor: [
      "Người cần giải khát",
      "Người vận động nhẹ",
      "Người thích vị tự nhiên",
    ],
    warningFor: ["Người cần kiểm soát đường huyết nên dùng khẩu phần vừa"],
    isVegetarian: true,
    image: "/foods/nuocdua.jpg",
  }),
  food({
    name: "Pepsi không calo",
    categorySlug: "do-uong-lanh-manh",
    price: 25000,
    description:
      "Nước ngọt không calo, phù hợp khi muốn giải khát nhưng không nạp năng lượng.",
    components: [{ name: "Pepsi không calo", grams: 330 }],
    macroType: "drink",
    sugar: 0,
    sodium: 35,
    fiber: 0,
    healthTags: ["đồ uống", "không calo", "không đường"],
    suitableFor: ["Người cần hạn chế calo", "Người muốn đồ uống không đường"],
    warningFor: ["Không nên dùng thay nước lọc hằng ngày"],
    isVegetarian: true,
    image: "/foods/pepsi.jpg",
  }),
  food({
    name: "Nước chanh",
    categorySlug: "do-uong-lanh-manh",
    price: 28000,
    description:
      "Nước chanh pha loãng không thêm đường; calo tính từ lượng chanh trong khẩu phần.",
    components: [{ name: "Chanh", grams: 60 }],
    macroType: "drink",
    sugar: 2,
    sodium: 5,
    fiber: 1,
    healthTags: ["đồ uống", "vitamin C", "ít calo"],
    suitableFor: ["Người cần giải khát", "Người muốn đồ uống ít calo"],
    warningFor: ["Người đau dạ dày nên cân nhắc do vị chua"],
    isVegetarian: true,
    image: "/foods/nuocchanh.jpg",
  }),
  food({
    name: "Nước chanh dâu tây",
    categorySlug: "do-uong-lanh-manh",
    price: 38000,
    description:
      "Chanh và dâu tây tươi, không thêm đường, vị chua ngọt tự nhiên.",
    components: [
      { name: "Chanh", grams: 40 },
      { name: "Dâu tây", grams: 120 },
    ],
    macroType: "drink",
    sugar: 9,
    sodium: 8,
    fiber: 3,
    healthTags: ["đồ uống", "trái cây", "ít calo"],
    suitableFor: ["Người cần giải khát", "Người thích vị chua ngọt nhẹ"],
    warningFor: ["Người đau dạ dày nên cân nhắc do vị chua"],
    isVegetarian: true,
    image: "/foods/chanhdautay.jpg",
  }),
];

const ensureDefaultUsers = async () => {
  const defaults = [
    {
      name: process.env.SEED_ADMIN_NAME || "Admin User",
      email: process.env.SEED_ADMIN_EMAIL || "admin@foodcare.ai",
      password: process.env.SEED_ADMIN_PASSWORD,
      role: "admin",
    },
    {
      name: process.env.SEED_USER_NAME || "Test User",
      email: process.env.SEED_USER_EMAIL || "user@foodcare.ai",
      password: process.env.SEED_USER_PASSWORD,
      role: "user",
    },
  ].filter((item) => item.password);

  if (defaults.length === 0) {
    console.warn("Skipping default users: configure SEED_ADMIN_PASSWORD or SEED_USER_PASSWORD.");
  }

  for (const item of defaults) {
    const exists = await User.findOne({ email: item.email });
    if (!exists) {
      await User.create({
        name: item.name,
        email: item.email,
        password: await bcrypt.hash(item.password, 10),
        role: item.role,
      });
    }
  }
};

const importData = async () => {
  try {
    await ensureDefaultUsers();

    await Category.bulkWrite(
      categories.map((category) => ({
        updateOne: {
          filter: { slug: category.slug },
          update: { $set: category },
          upsert: true,
        },
      })),
    );

    const createdCategories = await Category.find({
      slug: { $in: categories.map((category) => category.slug) },
    });
    const catMap = Object.fromEntries(
      createdCategories.map((category) => [category.slug, category._id]),
    );

    const sampleFoods = foods.map(({ categorySlug, ...item }) => ({
      ...item,
      category: catMap[categorySlug],
    }));

    await Food.bulkWrite(
      sampleFoods.map((item) => ({
        updateOne: {
          filter: { slug: item.slug },
          update: { $set: item },
          upsert: true,
        },
      })),
    );

    console.log(
      `Data synchronized successfully: ${createdCategories.length} categories, ${sampleFoods.length} foods.`,
    );
    process.exit();
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

importData();
